#!/bin/bash

version=$1

if [ -z "$version" ]; then
   echo "Argument is version in [major].[minor].[revision] format"
   exit 1
fi

ini_file="Config/DefaultGame.ini"

#Game Display
perl -pi -e "s/\d+\.\d+\.\d+/${version}/" $ini_file

git add $ini_file
git commit -m "Releasing version ${version}"
git tag -a "${version}" -m "version ${version}"

git push origin
git push origin "${version}"
